/* Import fidèle IRIS Studio : cette feuille ou ce composant conserve le langage éditorial et immersif du dépôt source. */
export const letsPlayDossiers = [
  {
    id: "gccdz-2026",
    index: "DOSSIER / 01",
    eyebrow: "GCCDZ 2026",
    title: "Partenaire média officiel, au cœur de l’événement.",
    description:
      "Dans sa publication du 9 février 2026, Let’s Play annonce rejoindre GCCDZ 2026 comme partenaire média officiel. La couverture annoncée réunit entretiens, temps forts et contenus dédiés à la communauté.",
    source: "Publication officielle Let’s Play · 09.02.2026",
    sourceHref: "https://www.instagram.com/p/DUi7HH2CFUJ/",
    actionLabel: "Lire l’annonce officielle",
    image: "assets/1000083809_f71dfb50.jpg",
    imageAlt: "Logo Games & Comic Con Dzair du GCCDZ 2026, partenaire média de Let’s Play",
  },
  {
    id: "short-film-contest",
    index: "DOSSIER / 02",
    eyebrow: "Concours de court métrage",
    title: "Une histoire courte, une scène à faire grandir.",
    description:
      "La chaîne officielle publie l’annonce d’un gagnant dans son concours de court métrage. Ce rendez-vous élargit le territoire Let’s Play vers les récits et la création portés par sa communauté.",
    source: "Vidéo officielle Let’s Play · 22:59",
    sourceHref: "https://www.youtube.com/watch?v=IB3UtlQdSSQ",
    actionLabel: "Voir l’annonce du gagnant",
  },
] as const;

export const letsPlayTeam = [
  {
    name: "Chafai Benamara · Chaft",
    role: "Éditeur en chef · gaming, cinéma & tech",
    text: "Éditeur en chef Gaming, Cinéma et Tech chez Iris Studio, Chafai Benamara est aussi identifié publiquement comme Editor in Chief & Host. À travers Let’s Play, il porte la conversation éditoriale entre jeu vidéo, culture, technologies et communauté.",
    marker: "ÉDITO",
    roleIcon: "editorial" as const,
    portrait: "assets/chafai-benamara-provided_1faa62af.jpg",
    portraitAlt: "Portrait fourni de Chafai Benamara",
    portraitCaption: "Portrait fourni / Chafai Benamara",
    source: "https://dz.linkedin.com/in/chafai-benamara-b7b87316",
    sourceLabel: "Voir le profil LinkedIn",
    linkedin: true,
  },
  {
    name: "Rebai Chentli",
    role: "Directeur d’agence · Co-animateur, Cinéma ta3 El 7it",
    text: "Directeur de l’agence Iris Studio et co-animateur de Cinéma ta3 El 7it, la rubrique qui met en discussion films, séries, animation et imaginaires pop culture.",
    episodeFormat: "Un film, une série, une sortie ou une actualité lance le débrief ; la discussion relie ensuite analyse des images, récit et culture pop.",
    episode: {
      label: "Voir l’épisode · concours du film court",
      url: "https://www.youtube.com/watch?v=IB3UtlQdSSQ&list=PLESXjoPag9EkfPAvP5CSq8CxL881aokt5",
    },
    marker: "CINÉMA",
    roleIcon: "presentation" as const,
    portrait: "assets/rebai-chentli_80c004cc.jpg",
    portraitAlt: "Portrait public de Rebai Chentli",
    portraitCaption: "Portrait / direction Iris Studio",
    source: "https://dz.linkedin.com/in/rebai-chentli-160a5332",
    sourceLabel: "Voir le profil LinkedIn",
    linkedin: true,
  },
  {
    name: "Naoufel Amokrane",
    role: "Community manager senior · Let’s Play",
    text: "Senior Community Manager de l’équipe Let’s Play, fonction communiquée par Iris Studio.",
    marker: "COMMUNAUTÉ",
    roleIcon: "community" as const,
    portrait: "assets/naoufel-amokrane-provided_d90f66ed.jpg",
    portraitAlt: "Portrait fourni de Naoufel Amokrane",
    portraitCaption: "Portrait fourni / Naoufel Amokrane",
    source: "https://www.linkedin.com/in/naoufel-amokrane-329a35257?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    sourceLabel: "Voir le profil LinkedIn",
    linkedin: true,
  },
  {
    name: "Salim Benmokhtar",
    role: "Design graphique · Iris Studio",
    text: "Son profil professionnel public le présente comme Graphic Designer Senior chez Iris Studio.",
    marker: "IMAGE",
    roleIcon: "graphicDesign" as const,
    portrait: "assets/salim-benmokhtar-provided_8a0bc794.png",
    portraitAlt: "Portrait fourni de Salim Benmokhtar",
    portraitCaption: "Portrait fourni / Salim Benmokhtar",
    source: "https://dz.linkedin.com/in/salim-benmokhtar-526408365",
    sourceLabel: "Voir le profil LinkedIn",
    linkedin: true,
  },
  {
    name: "Koussaila Ait Saada",
    role: "Édition vidéo · Iris Studio",
    text: "Son profil professionnel public le présente comme éditeur vidéo chez Iris Studio.",
    marker: "MONTAGE",
    roleIcon: "videoEditing" as const,
    portrait: "assets/koussaila-ait-saada-provided.jpg",
    portraitAlt: "Portrait fourni de Koussaila Ait Saada",
    portraitCaption: "Portrait fourni / Koussaila Ait Saada",
    source: "https://dz.linkedin.com/in/ait-saada-koussaila-153175350",
    sourceLabel: "Voir le profil LinkedIn",
    linkedin: true,
  },
  {
    name: "Ramy Baghli",
    role: "Co-présentateur · rubrique Easy Tech",
    text: "Co-présentateur d’Easy Tech, une rubrique qui rend des sujets technologiques, dont l’intelligence artificielle, accessibles à la communauté Let’s Play.",
    episodeFormat: "Un sujet technologique concret sert de point de départ, puis l’épisode le replace dans les usages du quotidien et du travail pour faciliter la discussion.",
    episode: {
      label: "Voir Easy Tech · l’IA avec Ramy",
      url: "https://www.youtube.com/watch?v=0vMonbvVpZQ",
    },
    marker: "EASY TECH",
    roleIcon: "presentation" as const,
    portrait: "assets/ramy-baghli-provided_9b78f5fa.jpg",
    portraitAlt: "Portrait fourni de Ramy Baghli",
    portraitCaption: "Portrait fourni / Ramy Baghli",
    source: undefined,
    sourceLabel: undefined,
    linkedin: false,
  },
] as const;

export const letsPlayScreenings = [
  {
    id: "gccdz-video",
    category: "REPORTAGE TERRAIN",
    title: "Games & Comic Con Dzair 2026 : Guests, Cosplay & Highlights !",
    detail: "15:17 · GCCDZ 2026",
    summary: "Une immersion au cœur de la convention, entre invités, cosplay et temps forts de la communauté.",
    href: "https://www.youtube.com/watch?v=HzigJZOxz2o",
    image: "assets/letsplay-episode-gccdz.webp",
  },
  {
    id: "short-film-video",
    category: "CONCOURS DE COURT MÉTRAGE",
    title: "عندنا فائز! مسابقة الفيلم القصير | Let’s Play",
    detail: "22:59 · Communauté créative",
    summary: "L’annonce du gagnant d’un concours qui ouvre Let’s Play aux récits imaginés par sa communauté.",
    href: "https://www.youtube.com/watch?v=IB3UtlQdSSQ",
    image: "assets/letsplay-episode-short-film-winner.webp",
  },
  {
    id: "retro-series-video",
    category: "ÉMISSION · POP CULTURE",
    title: "Nostalgia : Retro TV Legends That Shaped Our Imagination!",
    detail: "30:28 · Cinéma Ta3 l7ite",
    summary: "Un voyage dans les séries culte et les héros télé qui ont nourri l’imaginaire de toute une génération.",
    href: "https://www.youtube.com/watch?v=WcRpsKU8JDY",
    image: "assets/letsplay-episode-retro-series.webp",
  },
  {
    id: "ghost-of-yotei-video",
    category: "GAMING · PS5",
    title: "Ghost of Yōtei PS5 : Tsushima’s Successor or Just Hype?",
    detail: "12:47 · Décryptage gaming",
    summary: "Un regard sur l’univers de Ghost of Yōtei, son héritage et les attentes qu’il suscite auprès des joueurs.",
    href: "https://www.youtube.com/watch?v=SufCh7V9L3k",
    image: "assets/letsplay-episode-ghost-of-yotei.webp",
  },
  {
    id: "assassins-creed-video",
    category: "REVIEW · GAMING",
    title: "Assassin’s Creed Black Flag Resynced | Review",
    detail: "09:40 · Aventure pirate",
    summary: "La review Let’s Play d’un retour en mer qui revisite l’aventure pirate d’Assassin’s Creed.",
    href: "https://www.youtube.com/watch?v=0e5yXxfchLA",
    image: "assets/letsplay-episode-assassins-creed.webp",
  },
  {
    id: "game-awards-video",
    category: "GAMING · DÉBRIEF",
    title: "Game Awards 2025 Debrief : Clair Obscur et les grandes surprises",
    detail: "24:46 · Journal du Geek",
    summary: "Un débrief consacré aux annonces et aux temps forts des Game Awards, avec Clair Obscur : Expedition 33.",
    href: "https://www.youtube.com/watch?v=wl09SZI6wH0",
    image: "assets/letsplay-episode-game-awards.webp",
  },
  {
    id: "arc-raiders-video",
    category: "GAMING · TENDANCES",
    title: "Extraction Shooter Games Are Taking Over 2025! Deep Dive!",
    detail: "30:34 · ARC Raiders",
    summary: "Un épisode qui explore l’essor des jeux d’extraction et la place d’ARC Raiders dans cette nouvelle vague.",
    href: "https://www.youtube.com/watch?v=bsjWeFAgs-o",
    image: "assets/letsplay-episode-arc-raiders.webp",
  },
] as const;

export const letsPlayFeaturedScreening = letsPlayScreenings[0];

export const letsPlayTclReview = {
  category: "REVIEW TECH · TCL",
  index: "REVIEW / 03",
  duration: "13:28",
  title: "TCL C6K QD-MiniLED: The Ultimate 144 Hz Gaming TV Reveal!",
  summary:
    "Un épisode de Let’s Play consacré à la TCL C6K QD-MiniLED, publié dans la sélection Technology de la chaîne officielle.",
  image: "assets/letsplay-tcl-c6k-review.jpg",
  imageAlt: "Miniature officielle de la review Let’s Play consacrée à la TCL C6K QD-MiniLED",
  href: "https://www.youtube.com/watch?v=OEc9V9s3qu4",
} as const;

export const letsPlayInstagramVisuals = [
  {
    id: "gccdz-media-partner",
    category: "INSTAGRAM · GCCDZ 2026",
    title: "Let’s Play, partenaire média.",
    detail: "Visuel fourni · couverture GCCDZ 2026",
    image: "assets/gccdz-media-partner_1b439555.png",
    alt: "Let’s Play présenté comme partenaire média du GCCDZ 2026",
    href: "https://www.instagram.com/p/DUi7HH2CFUJ/",
  },
  {
    id: "sonic-35-years",
    category: "INSTAGRAM · POP CULTURE",
    title: "Sonic fête ses 35 ans.",
    detail: "Visuel fourni · culture gaming",
    image: "assets/sonic-35-years_de467599.png",
    alt: "Visuel Let’s Play célébrant les 35 ans de Sonic",
    href: "https://www.instagram.com/letsplay.officiel/",
  },
  {
    id: "crimson-desert",
    category: "INSTAGRAM · GCCDZ 2026",
    title: "Crimson Desert au GCCDZ.",
    detail: "Visuel fourni · animation de stand",
    image: "assets/crimson-desert-gccdz_67c0dd4d.png",
    alt: "Visuel Let’s Play pour Crimson Desert au GCCDZ 2026",
    href: "https://www.instagram.com/letsplay.officiel/",
  },
  {
    id: "gta-six",
    category: "INSTAGRAM · SORTIE GAMING",
    title: "Take my money, GTA VI.",
    detail: "Visuel fourni · conversation pop culture",
    image: "assets/gta-six-take-my-money_4f06380e.png",
    alt: "Visuel Let’s Play consacré à Grand Theft Auto VI",
    href: "https://www.instagram.com/letsplay.officiel/",
  },
  {
    id: "world-cup-2026",
    category: "INSTAGRAM · SPORT & GAMING",
    title: "Coupe du monde 2026.",
    detail: "Visuel fourni · rendez-vous communauté",
    image: "assets/world-cup-2026_632480e6.png",
    alt: "Visuel Let’s Play consacré à la Coupe du monde 2026",
    href: "https://www.instagram.com/letsplay.officiel/",
  },
] as const;
