/* Import fidèle IRIS Studio : cette feuille ou ce composant conserve le langage éditorial et immersif du dépôt source. */
export const sevenArenaDossiers = [
  {
    id: "alliance-champions",
    index: "DOSSIER / 01",
    eyebrow: "FF PRO LEAGUE · ALLIANCE",
    title: "L’Alliance au sommet de la Pro League.",
    description:
      "Dans son épisode final, 7ouma Arena by Djezzy accueille VENOM, présenté comme le capitaine de Team Alliance et champion de la FF Pro League, aux côtés de Supreme, manager de l’équipe.",
    source: "Épisode officiel 7ouma Arena · 41:40",
    sourceHref: "https://www.youtube.com/watch?v=RxOv92HDMQI",
    actionLabel: "Voir le Team Alliance Special",
  },
  {
    id: "pro-league-route",
    index: "DOSSIER / 02",
    eyebrow: "FF PRO LEAGUE · MONTH 2",
    title: "Une compétition qui se raconte au fil des matchs.",
    description:
      "La chaîne officielle suit la Pro League de ses étapes de qualification à la finale. Les rendez-vous éditoriaux font de la compétition un format à vivre, autant qu’un classement à suivre.",
    source: "Épisode officiel 7ouma Arena · 29:44",
    sourceHref: "https://www.youtube.com/watch?v=jJx6CmNaxCo",
    actionLabel: "Voir le lancement du Month 2",
  },
] as const;

export const sevenArenaHeroTrailer = {
  videoId: "e6vv15HN_Dg",
  title: "FF PROLEAGUE TEASER",
  href: "https://www.youtube.com/watch?v=e6vv15HN_Dg",
  embedSrc: "https://www.youtube.com/embed/e6vv15HN_Dg",
} as const;

export const sevenArenaFeaturedEpisode = {
  eyebrow: "Épisode en vedette",
  category: "Team Alliance Special",
  title: "VENOM, capitaine des champions.",
  description:
    "Dans l’épisode final de 7ouma Arena by Djezzy, VENOM, capitaine de Team Alliance et champion de la FF Pro League, est accueilli aux côtés de Supreme, manager de l’équipe.",
  duration: "41:40",
  videoId: "RxOv92HDMQI",
  href: "https://www.youtube.com/watch?v=RxOv92HDMQI",
  embedSrc: "https://www.youtube-nocookie.com/embed/RxOv92HDMQI",
  poster: "https://i.ytimg.com/vi/RxOv92HDMQI/hqdefault.jpg",
} as const;

export const sevenArenaScreenings = [
  {
    id: "alliance-special",
    category: "TEAM ALLIANCE SPECIAL",
    title: "VENOM, capitaine des champions.",
    detail: "41:40 · 36 k vues observées",
    href: "https://www.youtube.com/watch?v=RxOv92HDMQI",
    image: "https://i.ytimg.com/vi/RxOv92HDMQI/hqdefault.jpg",
  },
  {
    id: "pro-league-month-two",
    category: "FF PRO LEAGUE · MONTH 2",
    title: "Le retour de la compétition.",
    detail: "29:44 · 98 k vues observées",
    href: "https://www.youtube.com/watch?v=jJx6CmNaxCo",
    image: "https://i.ytimg.com/vi/jJx6CmNaxCo/hqdefault.jpg",
  },
  {
    id: "qualifiers-highlights",
    category: "FREE FIRE QUALIFIERS",
    title: "Les temps forts des qualifications.",
    detail: "35:02 · 130 k vues observées",
    href: "https://www.youtube.com/watch?v=tw8n0oi01Wg",
    image: "https://i.ytimg.com/vi/tw8n0oi01Wg/hqdefault.jpg",
  },
] as const;

export const sevenArenaVoices = [
  {
    id: "samy-charif",
    name: "Samy Charif",
    role: "Fondateur d’Egor Gaming · présentateur de 7ouma Arena",
    href: "https://www.instagram.com/charif.samy.dz/",
    image: "assets/samy-charif-egor-public-portrait_38be12ee.jpg",
    imageAlt: "Samy Charif, portrait public lié à Egor Gaming",
    imageNote: "Portrait public · réseau social",
  },
  {
    id: "seven",
    name: "Seven",
    role: "Présentateur · caster e-sport des formats 7ouma Arena",
    href: "https://www.instagram.com/seven.caster_/",
    image: "assets/seven-instagram-profile_50ea9921.jpg",
    imageAlt: "Seven, portrait public issu de son profil Instagram",
    imageNote: "Portrait public · Instagram",
  },

  {
    id: "mlagi",
    name: "MLAGI",
    role: "Invité d’un épisode officiel 7ouma Arena",
    href: "https://www.instagram.com/mlagi0/",
    image: "assets/mlagi-instagram-profile_0ffed2a5.jpg",
    imageAlt: "MLAGI, portrait public issu de son profil Instagram",
    imageNote: "Portrait public · Instagram",
  },
  {
    id: "boneja7",
    name: "Boneja7",
    role: "Les frères Bounjah · streaming et Free Fire",
    href: "https://www.instagram.com/boneja7_34/",
    image: "assets/iris-arena-boneja7-provided.jpg",
    imageAlt: "Portrait fourni de Boneja7",
    imageNote: "Portrait fourni",
  },
  {
    id: "bnl",
    name: "BNL",
    role: "Créateur invité · épisode 02 Ga3da Mobile",
    href: "https://www.instagram.com/bnl_yt/",
    image: "assets/bnl-instagram-profile_63088726.jpg",
    imageAlt: "BNL, portrait public issu de son profil Instagram",
    imageNote: "Portrait public · Instagram",
  },
  {
    id: "ra3d",
    name: "RA3D",
    role: "Créateur gaming · invité Free Fire",
    href: "https://www.instagram.com/ra3d_fr/",
    image: "assets/iris-arena-ra3d-provided.jpg",
    imageAlt: "Portrait fourni de RA3D",
    imageNote: "Portrait fourni",
  },
  {
    id: "beesto",
    name: "BEESTO",
    role: "Créateur gaming · invité Free Fire",
    href: "https://www.instagram.com/beesto_ff.31/",
    image: "assets/arena-ra3d-beesto.jpg",
    imageAlt: "BEESTO dans un visuel public de 7ouma Arena consacré à Free Fire",
    imageNote: "Visuel public · 7ouma Arena",
  },
  {
    id: "venom",
    name: "VENOM",
    role: "Capitaine de Team Alliance · champion FF Pro League",
    href: "https://www.youtube.com/watch?v=RxOv92HDMQI",
    image: "assets/arena-team-alliance.jpg",
    imageAlt: "VENOM avec Team Alliance dans une miniature officielle 7ouma Arena",
    imageNote: "Visuel officiel · Team Alliance",
  },
  {
    id: "supreme",
    name: "Supreme",
    role: "Manager de Team Alliance · invité Pro League",
    href: "https://www.youtube.com/watch?v=RxOv92HDMQI",
    image: "assets/arena-team-alliance.jpg",
    imageAlt: "Supreme avec Team Alliance dans une miniature officielle 7ouma Arena",
    imageNote: "Visuel officiel · Team Alliance",
  },
  {
    id: "boss-yt",
    name: "BOSS YT",
    role: "Créateur gaming · invité Free Fire",
    href: "https://www.instagram.com/7ouma.arena/",
    image: "assets/iris-arena-boss-yt-provided.jpg",
    imageAlt: "Portrait fourni de BOSS YT",
    imageNote: "Portrait fourni",
  },
  {
    id: "lady-gaming",
    name: "Lady Gaming",
    role: "Créatrice et streameuse · invitée 7ouma Arena",
    href: "https://www.instagram.com/7ouma.arena/",
    image: "assets/iris-arena-lady-gaming-provided.jpg",
    imageAlt: "Portrait fourni de Lady Gaming",
    imageNote: "Portrait fourni",
  },
] as const;

export const sevenArenaEcosystem = {
  label: "EGOR GAMING × 7OUMA ARENA",
  eyebrow: "Lien d’écosystème",
  title: "Un même terrain pour faire jouer l’e-sport.",
  description:
    "Samy Charif se présente publiquement comme CEO d’Egor Gaming et hôte de 7ouma Arena. Cette double présence relie le format 7ouma Arena à une plateforme compétitive pensée pour l’écosystème esport algérien.",
  note: "Relation présentée à partir de rôles publics déclarés ; aucun partenariat institutionnel distinct n’est affirmé ici.",
  platformHref: "https://egorgaming.com/",
  profileHref: "https://www.instagram.com/charif.samy.dz/",
} as const;

export const sevenArenaCredits = {
  eyebrow: "Remerciements & attribution",
  title: "7ouma Arena, un produit Djezzy.",
  description:
    "Djezzy porte 7ouma Arena comme projet e-sport et communautaire. Merci à la marque pour sa confiance et pour l’espace donné à une scène gaming algérienne plus visible, plus compétitive et plus connectée.",
  studio:
    "Imaginée et mise en action par Iris Studio, l’émission prend forme entre conception éditoriale, production de formats et activation communautaire.",
  chaft:
    "Chaft a participé activement à l’aventure de l’émission, au sein de cette mise en mouvement créative et éditoriale.",
  pillars: [
    { label: "Marque porteuse", value: "Djezzy" },
    { label: "Conception & activation", value: "Iris Studio" },
    { label: "Participation active", value: "Équipe projet" },
  ],
  activeParticipants: [
    {
      name: "Chaft",
      role: "Participation éditoriale active",
      description: "Contribution active à la mise en mouvement créative et éditoriale de l’émission.",
    },
    {
      name: "Samy « Egor »",
      role: "Présentateur",
      description: "Présentateur de 7ouma Arena et fondateur d’Egor Gaming.",
    },
    {
      name: "Seven",
      role: "Présentateur · caster e-sport",
      description: "Présentateur et caster e-sport associé aux formats de l’émission.",
    },
    {
      name: "Naoufel",
      role: "Community manager",
      description: "Community manager de l’émission et de ses échanges avec la communauté.",
    },
    {
      name: "Salim Benmokhtar",
      role: "Graphic design",
      description:
        "Charte graphique, visuels d’annonces et de résultats quotidiens, ainsi que les miniatures des épisodes.",
    },
    {
      name: "Kouceila",
      role: "Montage",
      description: "Montage des épisodes et des reels de 7ouma Arena.",
    },
    {
      name: "Ramy Baghli",
      role: "Planification",
      description: "Planification de l’émission et de ses rendez-vous éditoriaux.",
    },
  ],
} as const;

export const sevenArenaVisuals = [
  {
    id: "alliance-champions",
    kind: "resultat",
    category: "PUBLICATION INSTAGRAM · CHAMPIONS",
    title: "Team Alliance, champions.",
    detail: "Visuel HQ fourni · Pro League Free Fire",
    campaignPeriod: "Finale Pro League",
    image: "assets/alliance-champions_b6a53baf.jpg",
    alt: "Team Alliance présentée comme championne de la Pro League Free Fire par 7ouma Arena by Djezzy",
    href: "https://www.instagram.com/p/Dbyl8VIjTkt/",
  },
  {
    id: "lootbox-month-five",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · LOOTBOX",
    title: "Lootbox Month 5.",
    detail: "Visuel HQ fourni · récompenses Free Fire",
    campaignPeriod: "Month 5",
    image: "assets/lootbox-month-five_54036fb0.jpg",
    alt: "Visuel 7ouma Arena Lootbox Month 5 avec des récompenses Free Fire",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "lootbox-month-five-creators",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · VOTE",
    title: "Lootbox Month 5, côté créateurs.",
    detail: "Visuel HQ fourni · vote communautaire",
    campaignPeriod: "Month 5 · vote créateurs",
    image: "assets/lootbox-month-five-creators_934873fb.jpg",
    alt: "Visuel 7ouma Arena présentant les créateurs sélectionnés pour Lootbox Month 5",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "childrens-day-free-fire",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · COMMUNAUTÉ",
    title: "Happy Children’s Day.",
    detail: "Visuel HQ fourni · rendez-vous Free Fire",
    campaignPeriod: "Journée des enfants",
    image: "assets/childrens-day_9dd4423c.jpg",
    alt: "Visuel 7ouma Arena et Free Fire pour la Journée des enfants",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "wanted-dz-winner",
    kind: "resultat",
    category: "PUBLICATION INSTAGRAM · VAINQUEURS",
    title: "Wanted DZ, winners.",
    detail: "Visuel HQ fourni · résultat Pro League Free Fire",
    campaignPeriod: "Résultats Pro League",
    image: "assets/wanted-dz-winner_486ca2db.jpg",
    alt: "Wanted DZ annoncée comme équipe gagnante de la Pro League Free Fire par 7ouma Arena",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "semi-final-global-ranking",
    kind: "resultat",
    category: "PUBLICATION INSTAGRAM · CLASSEMENT",
    title: "Semi-final Global Ranking.",
    detail: "Visuel HQ fourni · résultats Day 3/3",
    campaignPeriod: "Demi-finale · Day 3/3",
    image: "assets/pro-league-semi-final-ranking_7e10df4a.jpg",
    alt: "Visuel 7ouma Arena du classement mondial de demi-finale Pro League Free Fire",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-pro-teams",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · PRO LEAGUE",
    title: "Pro teams invitées.",
    detail: "Visuel fourni · équipes e-sport de la Pro League",
    campaignPeriod: "Pro League",
    image: "assets/arena-pro-teams.png",
    alt: "Visuel 7ouma Arena présentant les équipes invitées de la Pro League Free Fire",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-casters",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · CASTERS",
    title: "Meet the casters.",
    detail: "Visuel fourni · présentation des casters de la Pro League",
    campaignPeriod: "Pro League",
    image: "assets/arena-casters.png",
    alt: "Visuel 7ouma Arena présentant les casters Seven, Niso, Siyaha et Flash",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-cash-prize",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · CASH PRIZE",
    title: "500 000 DA à gagner.",
    detail: "Visuel fourni · annonce de la récompense de la Pro League",
    campaignPeriod: "Pro League",
    image: "assets/arena-cash-prize.png",
    alt: "Visuel 7ouma Arena annonçant un cash prize de 500 000 dinars algériens pour la Pro League",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-registration-two-days",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · INSCRIPTIONS",
    title: "Deux jours avant les inscriptions.",
    detail: "Visuel fourni · compte à rebours Pro League",
    campaignPeriod: "J - 2",
    image: "assets/arena-registration-days-two.png",
    alt: "Visuel 7ouma Arena annonçant deux jours avant les inscriptions de la Pro League",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-registration-six-days",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · INSCRIPTIONS",
    title: "Six jours avant les inscriptions.",
    detail: "Visuel fourni · compte à rebours Pro League",
    campaignPeriod: "J - 6",
    image: "assets/arena-registration-days-six.png",
    alt: "Visuel 7ouma Arena annonçant six jours avant les inscriptions de la Pro League",
    href: "https://www.instagram.com/7ouma.arena/",
  },
  {
    id: "pro-league-registration-four-days",
    kind: "annonce",
    category: "PUBLICATION INSTAGRAM · INSCRIPTIONS",
    title: "Quatre jours avant les inscriptions.",
    detail: "Visuel fourni · compte à rebours Pro League",
    campaignPeriod: "J - 4",
    image: "assets/arena-registration-days-four.png",
    alt: "Visuel 7ouma Arena annonçant quatre jours avant les inscriptions de la Pro League",
    href: "https://www.instagram.com/7ouma.arena/",
  },
] as const;

export const sevenArenaVisualFilters = [
  { id: "tout", label: "Tout" },
  { id: "annonce", label: "Annonces" },
  { id: "resultat", label: "Résultats" },
] as const;

export const sevenArenaProLeague = {
  eyebrow: "FF PRO LEAGUE · FREE FIRE",
  titleLead: "La ligue où se joue",
  titleAccent: "le titre.",
  description:
    "7ouma Arena by Djezzy porte la FF Pro League featuring Free Fire : une saison de compétition e-sport mobile qui mène les équipes des inscriptions jusqu’à la Grand Final. Un compte à rebours officiel rythme l’ouverture des inscriptions, puis les qualifications désignent les douze finalistes. En Grand Final, une seule équipe peut être championne — « Only one can be the champion ».",
  stats: [
    { value: "500 000 DA", label: "Cash prize" },
    { value: "12", label: "Équipes en Grand Final" },
    { value: "04", label: "Casters officiels" },
    { value: "01", label: "Champion" },
  ],
  format: [
    {
      step: "01",
      title: "Inscriptions",
      text: "Un compte à rebours officiel, de J-7 à J-2, annonce l’ouverture des inscriptions à la Pro League.",
    },
    {
      step: "02",
      title: "Qualifications",
      text: "Les équipes s’affrontent pour décrocher leur place parmi les finalistes de la saison.",
    },
    {
      step: "03",
      title: "Grand Final",
      text: "Douze équipes, un seul titre : la Grand Final désigne le champion de la FF Pro League.",
    },
  ],
  casters: {
    title: "Aux micros",
    names: "Seven · Niso · Siyaha · Flash",
    text: "Quatre casters accompagnent la compétition et font vivre les matchs à la communauté.",
  },
  invited: {
    title: "Pro teams invitées",
    teams: ["USMA Esports", "Dragons Esport", "MCA Esports", "DNA", "Esports Miracles", "Stars DZ"],
    note: "La communauté est invitée à soutenir son équipe favorite.",
  },
  finalistsTitle: "Les 12 finalistes de la Grand Final",
  finalists: [
    "Wanted DZ",
    "Victors",
    "DNA",
    "All Down",
    "Alliance DZ",
    "HZ Team",
    "Cicatrice CG",
    "USMA ESP",
    "Strikers",
    "Elite Stars",
    "Hooligans",
    "Wrath Esport",
  ],
  teams:
    "Wanted DZ · Victors · DNA · All Down · Alliance DZ · HZ Team · Cicatrice CG · USMA ESP · Strikers · Elite Stars · Hooligans · Wrath Esport",
  editorial:
    "La FF Pro League est une compétition Free Fire pensée autour du jeu compétitif, des équipes et de la communauté. 7ouma Arena accompagne le tournoi en donnant de la visibilité aux matchs, aux résultats et aux acteurs de la scène e-sport algérienne.",
  note: "Tournoi présenté d’après la publication officielle 7ouma Arena. Le règlement complet n’est pas repris ici.",
  href: "https://www.instagram.com/p/DUBmgNcCCBT/",
  sourceLabel: "Voir la publication Instagram",
} as const;

export const sevenArenaProLeagueVisuals = [
  {
    id: "grand-final",
    category: "GRAND FINAL",
    title: "Only one can be the champion.",
    image: "assets/ff-pro-league-grand-final.jpg",
    alt: "Affiche Grand Final de la FF Pro League featuring Free Fire, 7ouma Arena by Djezzy, avec les douze équipes.",
  },
  {
    id: "lockup",
    category: "IDENTITÉ",
    title: "Pro League featuring Free Fire.",
    image: "assets/ff-pro-league-lockup.jpg",
    alt: "Logo Pro League featuring Free Fire.",
  },
  {
    id: "j7",
    category: "COUNTDOWN · J-7",
    title: "Le compte à rebours est lancé.",
    image: "assets/ff-pro-league-j7.jpg",
    alt: "Visuel 7ouma Arena : 7 days to go avant la FF Pro League.",
  },
  {
    id: "j6",
    category: "COUNTDOWN · J-6",
    title: "Before registration.",
    image: "assets/ff-pro-league-j6.jpg",
    alt: "Visuel 7ouma Arena : 6 days to go before registration.",
  },
  {
    id: "j5",
    category: "COUNTDOWN · J-5",
    title: "Le rendez-vous se rapproche.",
    image: "assets/ff-pro-league-j5.jpg",
    alt: "Visuel 7ouma Arena : 5 days to go avant la FF Pro League.",
  },
  {
    id: "j4",
    category: "COUNTDOWN · J-4",
    title: "هل أنت مستعد؟",
    image: "assets/ff-pro-league-j4.jpg",
    alt: "Visuel 7ouma Arena : 4 days to go avant la FF Pro League.",
  },
  {
    id: "j4-registration",
    category: "COUNTDOWN · J-4",
    title: "Before registration.",
    image: "assets/ff-pro-league-j4-registration.jpg",
    alt: "Visuel 7ouma Arena : 4 days to go before registration.",
  },
  {
    id: "j3",
    category: "COUNTDOWN · J-3",
    title: "الخط الأخير.",
    image: "assets/ff-pro-league-j3.jpg",
    alt: "Visuel 7ouma Arena : 3 days to go avant la FF Pro League.",
  },
  {
    id: "j2",
    category: "COUNTDOWN · J-2",
    title: "راكوم وجدين؟",
    image: "assets/ff-pro-league-j2.jpg",
    alt: "Visuel 7ouma Arena : 2 days before registration.",
  },
] as const;
